package top.ourck.beans;
// Generated 2019-3-17 22:07:24 by Hibernate Tools 5.3.6.Final

import java.util.List;

/**
 * Category generated by hbm2java
 */
@SuppressWarnings("serial")
public class Category  implements java.io.Serializable {

	private Integer id;
	private String name;
	private List<Product> productList;
	private List<List<Product>> productListByRow;
	
    public Category() {
    }

    public Category(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
    	return "Category " + "[" + name + "]";
    }

    public List<Product> getProductList() {
    	return productList;
    }
    
    public List<List<Product>> getProductListByRow() {
    	return productListByRow;
    }
    
    public void setProductList(List<Product> pList) {
    	this.productList = pList;
    }
    
    public void setProductListByRow(List<List<Product>> pListByRow) {
    	this.productListByRow = pListByRow;
    }
}


