package top.ourck.beans;
// Generated 2019-3-17 22:07:24 by Hibernate Tools 5.3.6.Final

/**
 * Orderitem generated by hbm2java
 */
@SuppressWarnings("serial")
public class Orderitem implements java.io.Serializable {

	private Integer id;
	private Product product;
	private User user;
	private Integer oid; // TODO private Order order;?
	private Integer number;

	public Orderitem() {
	}

	public Orderitem(Product product, User user, Integer oid, Integer number) {
		this.product = product;
		this.user = user;
		this.oid = oid;
		this.number = number;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

}
