package top.ourck.beans;
// Generated 2019-3-17 22:07:24 by Hibernate Tools 5.3.6.Final

/**
 * 订单项实体类
 * 订单(Order)的意思是，你清空购物车，结账的时候，上面会打印时间，消费总额<br>
 * 订单项(OrderItem)的意思是，这一次清空购物车，你消费了蜡烛2根，皮鞭1条，冰火两重天3次<br>
 * <br>
 * Orderitem generated by hbm2java
 * @author ourck
 */
@SuppressWarnings("serial")
public class OrderItem implements java.io.Serializable {

	private Integer id;
	private Product product;
	private User user;
	private Order order;
	private Integer number; // 购买数量

	public OrderItem() {
	}

	public OrderItem(Product product, User user, Order order, Integer number) {
		this.product = product;
		this.user = user;
		this.order = order;
		this.number = number;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

}
