package top.ourck.beans;
// Generated 2019-3-17 22:07:24 by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
@SuppressWarnings("serial")
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private String subTitle;
	private Float orignalPrice;
	private Float promotePrice;
	private Integer stock;
	private Date createDate;
	private Set<Productimage> productimages = new HashSet<Productimage>(0);
	private Set<Review> reviews = new HashSet<Review>(0);
	private Set<Orderitem> orderitems = new HashSet<Orderitem>(0);

	public Product() {
	}

	public Product(Category category, String name, String subTitle, Float orignalPrice, Float promotePrice,
			Integer stock, Date createDate) {
		this.category = category;
		this.name = name;
		this.subTitle = subTitle;
		this.orignalPrice = orignalPrice;
		this.promotePrice = promotePrice;
		this.stock = stock;
		this.createDate = createDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	public Float getOrignalPrice() {
		return this.orignalPrice;
	}

	public void setOrignalPrice(Float orignalPrice) {
		this.orignalPrice = orignalPrice;
	}

	public Float getPromotePrice() {
		return this.promotePrice;
	}

	public void setPromotePrice(Float promotePrice) {
		this.promotePrice = promotePrice;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set<Productimage> getProductimages() {
		return this.productimages;
	}

	public void setProductimages(Set<Productimage> productimages) {
		this.productimages = productimages;
	}

	public Set<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

	public Set<Orderitem> getOrderitems() {
		return this.orderitems;
	}

	public void setOrderitems(Set<Orderitem> orderitems) {
		this.orderitems = orderitems;
	}

}
