package top.ourck.beans;
// Generated 2019-3-17 22:07:24 by Hibernate Tools 5.3.6.Final

/**
 * Productimage generated by hbm2java
 */
@SuppressWarnings("serial")
public class ProductImage implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String type;

	public ProductImage() {
	}

	public ProductImage(Product product, String type) {
		this.product = product;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
