package top.ourck.beans;
// Generated 2019-3-17 22:07:24 by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.LinkedList;
import java.util.List;

/**
 * Product generated by hbm2java
 */
@SuppressWarnings("serial")
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private String subTitle;
	private Float orignalPrice;
	private Float promotePrice;
	private Integer stock;
	private Date createDate;
	private List<ProductImage> productImages = new LinkedList<ProductImage>();
	private List<Review> reviews = new LinkedList<Review>();
	private List<OrderItem> orderItems = new LinkedList<OrderItem>();

	// OURCK: Business relative.
	private ProductImage firstImage;
	private int reviewCount;
	private int saleCount;

	public Product() {
	}

	public Product(Category category, String name, String subTitle, Float orignalPrice, Float promotePrice,
			Integer stock, Date createDate) {
		this.category = category;
		this.name = name;
		this.subTitle = subTitle;
		this.orignalPrice = orignalPrice;
		this.promotePrice = promotePrice;
		this.stock = stock;
		this.createDate = createDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	public Float getOrignalPrice() {
		return this.orignalPrice;
	}

	public void setOrignalPrice(Float orignalPrice) {
		this.orignalPrice = orignalPrice;
	}

	public Float getPromotePrice() {
		return this.promotePrice;
	}

	public void setPromotePrice(Float promotePrice) {
		this.promotePrice = promotePrice;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public List<ProductImage> getProductimages() {
		return this.productImages;
	}

	public void setProductimages(List<ProductImage> productImages) {
		this.productImages = productImages;
	}

	public List<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(List<Review> reviews) {
		this.reviews = reviews;
	}

	public List<OrderItem> getOrderitems() {
		return this.orderItems;
	}

	public void setOrderitems(List<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	// OURCK 
	
	public ProductImage getFirstImage() {
		return firstImage;
	}

	public void setFirstImage(ProductImage firstImage) {
		this.firstImage = firstImage;
	}

	public int getReviewCount() {
		return reviewCount;
	}

	public void setReviewCount(int reviewCount) {
		this.reviewCount = reviewCount;
	}

	public int getSaleCount() {
		return saleCount;
	}

	public void setSaleCount(int saleCount) {
		this.saleCount = saleCount;
	}

}
