package top.ourck.beans;
// Generated 2019-3-17 22:07:24 by Hibernate Tools 5.3.6.Final

/**
 * Propertyvalue generated by hbm2java
 */
@SuppressWarnings("serial")
public class PropertyValue implements java.io.Serializable {

	private Integer id;
	private Property property;
	private Product product;
	private String value;

	public PropertyValue() {
	}

	public PropertyValue(Property property, Product product, String value) {
		this.property = property;
		this.setProduct(product);
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Property getProperty() {
		return this.property;
	}

	public void setProperty(Property property) {
		this.property = property;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
