package top.ourck.beans;
// Generated 2019-3-17 22:07:24 by Hibernate Tools 5.3.6.Final


/**
 * User generated by hbm2java
 */
@SuppressWarnings("serial")
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	private String password;

	public User() {
	}

	public User(String name, String password) {
		this.name = name;
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		return "User " + "[" + id + ", " + name + ", " + password + "]";
	}
	
	/**
	 * Extended method.
	 * @return Anonymous name of an User.
	 */
	public String getAnonymousName(){
        if(null==name)
            return null;
         
        if(name.length()<=1)
            return "*";
         
        if(name.length()==2)
            return name.substring(0,1) +"*";
         
        char[] cs =name.toCharArray();
        for (int i = 1; i < cs.length-1; i++) {
            cs[i]='*';
        }
        return new String(cs);
         
    }
}
